/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package layout;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author ACER
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButtonFullScreen
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBTN = new javax.swing.JPanel();
        btnTA = new javax.swing.JButton();
        btnTA1 = new javax.swing.JButton();
        btnTA2 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        panelIMG = new javax.swing.JPanel();
        lblFree = new javax.swing.JLabel();
        lblTA1 = new javax.swing.JLabel();
        lblTA2 = new javax.swing.JLabel();
        lblTA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penamil Gambar Full Screen");
        setUndecorated(true);

        panelBTN.setBackground(new java.awt.Color(0, 204, 204));
        panelBTN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplikasi Penampil Gambar Button Fullscreen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 12))); // NOI18N

        btnTA.setText("Tuna Asap");
        btnTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAActionPerformed(evt);
            }
        });
        panelBTN.add(btnTA);

        btnTA1.setText("Tuna Asap 1");
        btnTA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTA1ActionPerformed(evt);
            }
        });
        panelBTN.add(btnTA1);

        btnTA2.setText("Tuna Asap 2");
        btnTA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTA2ActionPerformed(evt);
            }
        });
        panelBTN.add(btnTA2);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelBTN.add(btnClear);

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        panelBTN.add(btnExit);

        getContentPane().add(panelBTN, java.awt.BorderLayout.PAGE_START);

        panelIMG.setLayout(new java.awt.CardLayout());

        lblFree.setBackground(new java.awt.Color(255, 255, 255));
        lblFree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFree.setName("null"); // NOI18N
        panelIMG.add(lblFree, "0");
        lblFree.getAccessibleContext().setAccessibleName("0");
        lblFree.getAccessibleContext().setAccessibleDescription("null");

        lblTA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuna_asap_1.jpg"))); // NOI18N
        lblTA1.setName("null"); // NOI18N
        panelIMG.add(lblTA1, "1");
        lblTA1.getAccessibleContext().setAccessibleName("1");
        lblTA1.getAccessibleContext().setAccessibleDescription("null");

        lblTA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuna_asap_2.jpg"))); // NOI18N
        lblTA2.setName("null"); // NOI18N
        panelIMG.add(lblTA2, "2");
        lblTA2.getAccessibleContext().setAccessibleName("2");
        lblTA2.getAccessibleContext().setAccessibleDescription("null");

        lblTA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tuna_asap.jpg"))); // NOI18N
        lblTA.setName("null"); // NOI18N
        panelIMG.add(lblTA, "3");
        lblTA.getAccessibleContext().setAccessibleName("3");
        lblTA.getAccessibleContext().setAccessibleDescription("null");

        getContentPane().add(panelIMG, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAActionPerformed
        CardLayout cl = (CardLayout) (panelIMG.getLayout());
        cl.show (panelIMG, "1");
    }//GEN-LAST:event_btnTAActionPerformed

    private void btnTA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTA1ActionPerformed
        CardLayout cl = (CardLayout) (panelIMG.getLayout());
        cl.show (panelIMG, "2");
    }//GEN-LAST:event_btnTA1ActionPerformed

    private void btnTA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTA2ActionPerformed
        CardLayout cl = (CardLayout) (panelIMG.getLayout());
        cl.show (panelIMG, "3");
    }//GEN-LAST:event_btnTA2ActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        CardLayout cl = (CardLayout) (panelIMG.getLayout());
        cl.show (panelIMG, "0");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PilihGambarButtonFullScreen().setVisible(true);
                PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
                
                GraphicsDevice device = 
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTA;
    private javax.swing.JButton btnTA1;
    private javax.swing.JButton btnTA2;
    private javax.swing.JLabel lblFree;
    private javax.swing.JLabel lblTA;
    private javax.swing.JLabel lblTA1;
    private javax.swing.JLabel lblTA2;
    private javax.swing.JPanel panelBTN;
    private javax.swing.JPanel panelIMG;
    // End of variables declaration//GEN-END:variables
}
